name: Test

on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types: [edited, dismissed]
  workflow_dispatch:


jobs:
  list-compartment-ids:
    runs-on: ubuntu-latest
    name: Use the run-oci-cli-command to retrieve a list of compartment ids
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve the OCID of a named compartment in tenancy
        uses: ./.github/actions/
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='${{ secrets.OCI_COMPARTMENT_NAME }}'].id"