name: containerize

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      working-directory: ../../container
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: iad.ocir.io
      #     username: ${{ secrets.OCI_CR_PRINCIPAL }}
      #     password: ${{ secrets.OCI_CR_CREDENTIAL }}


      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: generic
          compartment: ${{ secrets.OCI_CR_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_CR_CREDENTIAL }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./container
          push: false
          tags: iad.ocir.io/idbjyurhyjpo/generic/frontend:0

      - name: Docker Push
        run: docker push "iad.ocir.io/idbjyurhyjpo/generic/frontend:0"

      # - name: Tag and push a container image
      #   id: tag-and-push-image
      #   run: |
      #     docker tag "generic/frontend:latest" "iad.ocir.io/idbjyurhyjpo/generic:0"
      #     docker push "iad.ocir.io/idbjyurhyjpo/generic:0"
      # - run: pwd
      # - run: ls
      # - 
      #   name: Build & push Docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: generic/frontend
      #     tags: v0, latest
      #     registry: iad.ocir.io
      #     # directory: ./container
      #     dockerfile: Dockerfile
      #     username: ${{ secrets.OCI_CR_PRINCIPAL }}
      #     password: ${{ secrets.OCI_CR_CREDENTIAL }}