name: containerize

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    # env:
    #   working-directory: ./container
    # defaults:
    #   run:
    #     working-directory: ${{ env.working-directory }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: iad.ocir.io
          username: ${{ secrets.OCI_CR_PRINCIPAL }}
          password: ${{ secrets.OCI_CR_CREDENTIAL }}
      # -
        # name: Build and push
        # uses: docker/build-push-action@v5
        # with:
        #   context: ./container
        #   push: true
        #   tags: generic/app:latest
      - 
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: generic/frontend
          tags: v0, latest
          registry: iad.ocir.io
          dockerfile: ./container/Dockerfile
          username: ${{ secrets.OCI_CR_PRINCIPAL }}
          password: ${{ secrets.OCI_CR_CREDENTIAL }}